# Generated by Django 5.2.4 on 2025-07-17 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudantes',
            new_name='Estudante',
        ),
    ]
